In [1]:
import numpy as np

In [2]:
""" Creating a 1-10 array """
x = np.arange(1, 11)

In [3]:
""" Making the array 2d """
x = x.reshape(2, 5)
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [4]:
""" Accessing the 3d element """
x[0, 2]

3

In [5]:
""" Multiply each element by 2 """
# for i in range(len(x)):
#     for j in range(len(x[i])):
#         x[i][j] *= 2
# x
x = x * 2
x

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20]])

In [6]:
"""" Getting mean """
x_mean = np.mean(x)
"""" Getting the diviation """
x_sd = np.std(x)
x_sd, x_mean

(5.744562646538029, 11.0)

In [7]:
"""" Concatenating 2 arrays horizontally """
arr1 = np.arange(7)
arr2 = np.arange(6)
y = np.hstack((arr1, arr2)) # same as np.concatenate([arr1, arr2])
y

array([0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5])

In [8]:
""" Greater then 5 """
# for _ in y:
#     if _ > 5:
#         print(_)
z = y[y>5]
z

array([6])

In [9]:
""" Matrix multiplication, """
arr3 = np.arange(1, 11).reshape(2, 5)
arr4 = np.arange(1, 11).reshape(2, 5)
m = np.matmul(arr3, arr4.T) # transpoing the form
m, arr3, arr4.T

(array([[ 55, 130],
        [130, 330]]),
 array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]),
 array([[ 1,  6],
        [ 2,  7],
        [ 3,  8],
        [ 4,  9],
        [ 5, 10]]))

In [10]:
np.save("Multiplied_array.npy", m)  # Save the multiplied array with the .npy extension
load_arr = np.load("Multiplied_array.npy")  # Load the multiplied array with the .npy extension
load_arr


array([[ 55, 130],
       [130, 330]])

In [11]:
""" Making random matrix """
random_arr = np.random.randint(2, size =(3,3))
random_arr

array([[1, 0, 0],
       [1, 0, 1],
       [0, 0, 0]])

In [12]:
""""Array stacking verically"""
random_arr_1 = np.random.randint(1, 11, size =(1,3))
random_arr_2 = np.random.randint(1, 11, size =(3,3))
st = np.vstack([random_arr_1, random_arr_2])
st

array([[ 5,  1,  1],
       [ 6,  3, 10],
       [ 7, 10,  1],
       [ 2,  8,  4]])

In [13]:
""" Displaying unique elements and count them """
arr = np.array([1, 2, 2, 3, 4, 4, 4])
elements, count = np.unique(arr, return_counts=True)
print("Elements", elements)
print("Count", count)

Elements [1 2 3 4]
Count [1 2 1 3]


In [14]:
""" Reshaping and shapin back """
arr = np.arange(1, 10).reshape(3, 3)
arr_1 = np.hstack(arr) #making 1d or arr.flatten()
arr_1.reshape((3,3)) #turning back into 3d or np.reshape(arr_1, (3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
""" Changing all odd numbers into -1 """
arr = np.arange(1, 10).reshape(3,3)
arr[arr % 2 !=0] = -1
arr

array([[-1,  2, -1],
       [ 4, -1,  6],
       [-1,  8, -1]])

In [16]:
"""" Extracting all greater then mean """
arr = np.random.randint(1, 1000, size =(3,3))
arr_m = np.mean(arr)
arr_g = arr[arr > arr_m]
arr, arr_m, arr_g

(array([[769, 190, 223],
        [ 48, 988, 982],
        [144, 932, 981]]),
 584.1111111111111,
 array([769, 988, 982, 932, 981]))

In [17]:
""" Making a copy of an array """
arr = np.arange(1, 10).reshape(3,3)
y = np.array(arr, copy=True)  
y[0] = -3
arr, y

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[-3, -3, -3],
        [ 4,  5,  6],
        [ 7,  8,  9]]))

In [18]:
""" Matmul again """
# A = np.random.randint(1, 100, size=(4,3))
# B = np.random.randint(1, 100, size=(3,4))
# C= np.matmul(A, B)
# C
# The @ operator for multiplication invokes the matmul() C = A @ B
np.random.seed(10)
A = np.random.rand(4, 3) #return floar from 0 to 1
B = np.random.rand(3, 4)
C = np.dot(A, B)
D = np.matmul(A, B)
print("A",A,"\nB", B,"\nC", C, "\nD", D)
C==D

A [[0.77132064 0.02075195 0.63364823]
 [0.74880388 0.49850701 0.22479665]
 [0.19806286 0.76053071 0.16911084]
 [0.08833981 0.68535982 0.95339335]] 
B [[0.00394827 0.51219226 0.81262096 0.61252607]
 [0.72175532 0.29187607 0.91777412 0.71457578]
 [0.54254437 0.14217005 0.37334076 0.67413362]] 
C [[0.36180549 0.49120726 0.88240364 0.91444642]
 [0.48471872 0.56099317 1.14993632 0.96642591]
 [0.64144922 0.34746948 0.92208141 0.7787788 ]
 [1.01226907 0.38083108 1.05673289 1.18656647]] 
D [[0.36180549 0.49120726 0.88240364 0.91444642]
 [0.48471872 0.56099317 1.14993632 0.96642591]
 [0.64144922 0.34746948 0.92208141 0.7787788 ]
 [1.01226907 0.38083108 1.05673289 1.18656647]]


array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [19]:
"""Reshaping once again"""
A=np.random.rand(9,7)
B = A.reshape(3,21)
B

array([[0.44183317, 0.43401399, 0.61776698, 0.51313824, 0.65039718,
        0.60103895, 0.8052232 , 0.52164715, 0.90864888, 0.31923609,
        0.09045935, 0.30070006, 0.11398436, 0.82868133, 0.04689632,
        0.62628715, 0.54758616, 0.819287  , 0.19894754, 0.8568503 ,
        0.35165264],
       [0.75464769, 0.29596171, 0.88393648, 0.32551164, 0.1650159 ,
        0.39252924, 0.09346037, 0.82110566, 0.15115202, 0.38411445,
        0.94426071, 0.98762547, 0.45630455, 0.82612284, 0.25137413,
        0.59737165, 0.90283176, 0.53455795, 0.59020136, 0.03928177,
        0.35718176],
       [0.07961309, 0.30545992, 0.33071931, 0.7738303 , 0.03995921,
        0.42949218, 0.31492687, 0.63649114, 0.34634715, 0.04309736,
        0.87991517, 0.76324059, 0.87809664, 0.41750914, 0.60557756,
        0.51346663, 0.59783665, 0.26221566, 0.30087131, 0.02539978,
        0.30306256]])

In [20]:
np.random.seed(10)
B = np.random.rand(9,7)
B = np.hstack(B)
print(B)
ten_twenty = B[10:21] # using indices   
ten_twenty

[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701 0.22479665
 0.19806286 0.76053071 0.16911084 0.08833981 0.68535982 0.95339335
 0.00394827 0.51219226 0.81262096 0.61252607 0.72175532 0.29187607
 0.91777412 0.71457578 0.54254437 0.14217005 0.37334076 0.67413362
 0.44183317 0.43401399 0.61776698 0.51313824 0.65039718 0.60103895
 0.8052232  0.52164715 0.90864888 0.31923609 0.09045935 0.30070006
 0.11398436 0.82868133 0.04689632 0.62628715 0.54758616 0.819287
 0.19894754 0.8568503  0.35165264 0.75464769 0.29596171 0.88393648
 0.32551164 0.1650159  0.39252924 0.09346037 0.82110566 0.15115202
 0.38411445 0.94426071 0.98762547 0.45630455 0.82612284 0.25137413
 0.59737165 0.90283176 0.53455795]


array([0.68535982, 0.95339335, 0.00394827, 0.51219226, 0.81262096,
       0.61252607, 0.72175532, 0.29187607, 0.91777412, 0.71457578,
       0.54254437])

In [21]:
""" Splitting and Stacking"""
np.random.seed(10)
X = np.random.randint(1, 100, size = (3,4))
Y = np.random.randint(1, 100, size = (3,4))
vertical_Stack = np.vstack((X, Y)) # takes 1 positional argument but 2 were given --> solution (())
horizontal_Stack = np.hstack((X, Y))
# X = np.hstack(X)
# Y = np.vstack(Y)
# X = X.reshape(3,4)
vertical_Stack, horizontal_Stack
split_v = np.vsplit(vertical_Stack, 2) #splits into 2 equal vertical array
split_h = np.hsplit(horizontal_Stack, 2) # splits like this [1, 2], [1, 2] --> [1, 1], [2,2]

vertical_Stack, horizontal_Stack, "split_v", split_v,"split_h", split_h

(array([[10, 16, 65, 29],
        [90, 94, 30,  9],
        [74,  1, 41, 37],
        [17, 12, 55, 89],
        [63, 34, 73, 79],
        [50, 52, 55, 78]]),
 array([[10, 16, 65, 29, 17, 12, 55, 89],
        [90, 94, 30,  9, 63, 34, 73, 79],
        [74,  1, 41, 37, 50, 52, 55, 78]]),
 'split_v',
 [array([[10, 16, 65, 29],
         [90, 94, 30,  9],
         [74,  1, 41, 37]]),
  array([[17, 12, 55, 89],
         [63, 34, 73, 79],
         [50, 52, 55, 78]])],
 'split_h',
 [array([[10, 16, 65, 29],
         [90, 94, 30,  9],
         [74,  1, 41, 37]]),
  array([[17, 12, 55, 89],
         [63, 34, 73, 79],
         [50, 52, 55, 78]])])

In [22]:
""" Root, exponential, floor """
np.random.seed(10)
A = np.random.rand(10) * 3
sq = np.sqrt(A) 
ex = np.exp(A)
floor = np.floor(A)
A, sq, ex, floor

(array([2.31396193, 0.06225585, 1.9009447 , 2.24641165, 1.49552104,
        0.67438994, 0.59418859, 2.28159214, 0.50733251, 0.26501944]),
 array([1.52117124, 0.24951122, 1.37874751, 1.49880341, 1.22291498,
        0.82121248, 0.7708363 , 1.510494  , 0.71227278, 0.51480039]),
 array([10.11441799,  1.06423459,  6.69221362,  9.45375151,  4.46166064,
         1.96283516,  1.81156044,  9.79225862,  1.66085497,  1.30345632]),
 array([2., 0., 1., 2., 1., 0., 0., 2., 0., 0.]))

In [23]:
""" Boolean Operations """
np.random.seed(10)
C= np.random.rand(20)
B = C[(C > 0.5) & (C < 0.7)]
#B=C[0.5<C<0.7] Doens't work
B

array([0.63364823, 0.68535982, 0.51219226, 0.61252607])

In [24]:
""" Broadcasting """
np.random.seed(10)
# M = np.random.randint(0, 4, size=(5,5))
# V = np.arange(1, 6)
# C = M + V
# M, V, C
M = np.zeros((5, 5)) + np.arange(5)
v = np.array([1, 2, 3, 4, 5])
D = M + v 
M, v, D
# When adding a 2d array and 1 d array, 1d is added to all the rows of 2d array

(array([[0., 1., 2., 3., 4.],
        [0., 1., 2., 3., 4.],
        [0., 1., 2., 3., 4.],
        [0., 1., 2., 3., 4.],
        [0., 1., 2., 3., 4.]]),
 array([1, 2, 3, 4, 5]),
 array([[1., 3., 5., 7., 9.],
        [1., 3., 5., 7., 9.],
        [1., 3., 5., 7., 9.],
        [1., 3., 5., 7., 9.],
        [1., 3., 5., 7., 9.]]))

In [25]:
""" Sorting """
np.random.seed(10)
R = np.random.randint(1,100, size=(4,6))
x = np.sort(R, axis=0) # sorts the axis down
y = np.sort(R, axis=1) # sorts the axis 
R, x, y

(array([[10, 16, 65, 29, 90, 94],
        [30,  9, 74,  1, 41, 37],
        [17, 12, 55, 89, 63, 34],
        [73, 79, 50, 52, 55, 78]]),
 array([[10,  9, 50,  1, 41, 34],
        [17, 12, 55, 29, 55, 37],
        [30, 16, 65, 52, 63, 78],
        [73, 79, 74, 89, 90, 94]]),
 array([[10, 16, 29, 65, 90, 94],
        [ 1,  9, 30, 37, 41, 74],
        [12, 17, 34, 55, 63, 89],
        [50, 52, 55, 73, 78, 79]]))

In [26]:
""" Count and unique"""
np.random.seed(10)
U = np.random.randint(1, 10, size=(5,5))
elements, count = np.unique(U, return_counts=True)
elements, count


(array([1, 2, 4, 5, 6, 7, 9]), array([4, 5, 3, 4, 1, 4, 4], dtype=int64))

In [27]:
""""Saving as txt"""
np.random.seed(10)
U = np.random.randint(1, 10, size=(5, 5))
np.savetxt("Multiplied_array.txt", U)  # Savetxt
load_arr = np.loadtxt("Multiplied_array.txt")  # Loadtxt the array with the .txt extension
U

array([[5, 1, 2, 1, 2],
       [9, 1, 9, 7, 5],
       [4, 1, 5, 7, 9],
       [2, 9, 5, 2, 4],
       [7, 6, 4, 7, 2]])