In [1]:
import numpy as np

In [17]:
""" Creating a 1-10 array """
x = np.arange(1, 11)

In [18]:
""" Making the array 2d """
x = x.reshape(2, 5)
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [4]:
""" Accessing the 3d element """
x[0, 2]

3

In [19]:
""" Multiply each element by 2 """
# for i in range(len(x)):
#     for j in range(len(x[i])):
#         x[i][j] *= 2
# x
x = x * 2
x

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20]])

In [20]:
"""" Getting mean """
x_mean = np.mean(x)
"""" Getting the diviation """
x_sd = np.std(x)
x_sd, x_mean

(5.744562646538029, 11.0)

In [29]:
"""" Concatenating 2 arrays horizontally """
arr1 = np.arange(7)
arr2 = np.arange(6)
y = np.hstack((arr1, arr2)) # same as np.concatenate([arr1, arr2])
y

array([0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5])