In [29]:
import numpy as np

In [30]:
""" Creating a 1-10 array """
x = np.arange(1, 11)

In [31]:
""" Making the array 2d """
x = x.reshape(2, 5)
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [32]:
""" Accessing the 3d element """
x[0, 2]

3

In [33]:
""" Multiply each element by 2 """
# for i in range(len(x)):
#     for j in range(len(x[i])):
#         x[i][j] *= 2
# x
x = x * 2
x

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20]])

In [34]:
"""" Getting mean """
x_mean = np.mean(x)
"""" Getting the diviation """
x_sd = np.std(x)
x_sd, x_mean

(5.744562646538029, 11.0)

In [35]:
"""" Concatenating 2 arrays horizontally """
arr1 = np.arange(7)
arr2 = np.arange(6)
y = np.hstack((arr1, arr2)) # same as np.concatenate([arr1, arr2])
y

array([0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5])

In [36]:
""" Greater then 5 """
# for _ in y:
#     if _ > 5:
#         print(_)
z = y[y>5]
z

array([6])

In [37]:
""" Matrix multiplication, """
arr3 = np.arange(1, 11).reshape(2, 5)
arr4 = np.arange(1, 11).reshape(2, 5)
m = np.matmul(arr3, arr4.T) # transpoing the form
m, arr3, arr4.T

(array([[ 55, 130],
        [130, 330]]),
 array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]),
 array([[ 1,  6],
        [ 2,  7],
        [ 3,  8],
        [ 4,  9],
        [ 5, 10]]))

In [38]:
np.save("Multiplied_array.npy", m)  # Save the multiplied array with the .npy extension
load_arr = np.load("Multiplied_array.npy")  # Load the multiplied array with the .npy extension
load_arr


array([[ 55, 130],
       [130, 330]])