Grade Book Management System

In [30]:
import numpy as np

In [41]:
""""Data initalization """
grades = np.array([
    [78, 44, 74], # Maths, English, Literature
    [43, 31, 74],
    [11, 13, 44],
    [85, 31, 11]
])
grades

array([[78, 44, 74],
       [43, 31, 74],
       [11, 13, 44],
       [85, 31, 11]])

In [32]:
""" Calculating average for subject """
# grades_maths = grades[0:,0].mean()
# grades_eng = grades[0:, 1].mean()
# grades_lit = grades[0:, 2].mean()
# print(grades_maths, grades_eng, grades_lit)
subject_avg = np.mean(grades, axis=0) #axis = 0 goes in colmns |
print(subject_avg)

[54.25 29.75 50.75]


In [33]:
""" Calculating average for a student """
student_avg = np.mean(grades, axis=1)
print(student_avg)

[65.33333333 49.33333333 22.66666667 42.33333333]


In [46]:
"""" Grade Modification """
changes_grades = np.array(grades, copy=True)  
print(changes_grades)
changes_grades[0:, 1] = 85
changes_grades

[[78 44 74]
 [43 31 74]
 [11 13 44]
 [85 31 11]]


array([[78, 85, 74],
       [43, 85, 74],
       [11, 85, 44],
       [85, 85, 11]])

In [48]:
subject_avg = np.mean(changes_grades, axis=0) #axis = 0 goes in colmns |
print(subject_avg)
student_avg = np.mean(changes_grades, axis=1)
print(student_avg)

[54.25 85.   50.75]
[79.         67.33333333 46.66666667 60.33333333]


In [49]:
"""Display results"""""

print("Average Grades for each Subject:", subject_avg)
print("Average Grade for each Student:", student_avg)

Average Grades for each Subject: [54.25 85.   50.75]
Average Grade for each Student: [79.         67.33333333 46.66666667 60.33333333]
