Second mini project

In [1]:
import numpy as np

In [2]:
""""Creating the data"""
np.random.seed(10)
number_of_students = 20 # one row = 1 studnet
number_of_subjects = 5 # one column = 1 subject
marks = np.random.randint(1, 100, size =(number_of_students, number_of_subjects))
marks

array([[10, 16, 65, 29, 90],
       [94, 30,  9, 74,  1],
       [41, 37, 17, 12, 55],
       [89, 63, 34, 73, 79],
       [50, 52, 55, 78, 70],
       [14, 26, 14, 93, 87],
       [31, 31, 90, 13, 66],
       [32, 58, 37, 28, 19],
       [94, 78, 23, 24, 95],
       [12, 29, 75, 89, 10],
       [16, 19, 81, 72, 89],
       [12, 18, 47,  8, 76],
       [29, 34, 85, 97, 89],
       [45,  6,  5, 72, 89],
       [89, 51, 55, 35, 16],
       [78, 89, 16,  7, 86],
       [23, 12, 13, 93, 97],
       [63, 58, 80, 43, 58],
       [98, 51, 46, 41, 90],
       [74, 38,  1, 19, 24]])

In [3]:
""""Calculating the mean for a subject"""
subject_mean = np.mean(marks, axis = 0)
subject_mean

array([49.7, 39.8, 42.4, 50. , 64.3])

In [4]:
"""Calculating the mean for a student"""
student_mean = np.mean(marks, axis = 1)
student_mean

array([42. , 41.6, 32.4, 67.6, 61. , 46.8, 46.2, 34.8, 62.8, 43. , 55.4,
       32.2, 66.8, 43.4, 49.2, 55.2, 47.6, 60.4, 65.2, 31.2])

In [5]:
""" The highest and lowest subject score"""
min = np.min(marks, axis=0)
max = np.max(marks, axis=0)
#print("The highest score in every subject is", max, "The lowest score in every subject is", min)
min_s = np.min(marks, axis=1)
max_s = np.max(marks, axis=1)
#max_s = np.vstack(max_s)
#print("The highest score for every student is", max_s, "The lowest score for every student is", min_s)

In [9]:
""" Idenitgy the students who have failed the class"""
#failed_students = marks[marks<50]
failed_students = np.sum(marks < 50, axis = 0) # summs up all of the students who scored under 50 in this subject, axis=0
for i, num in enumerate(failed_students):
    print(f"The {i+1} subject was failed by {num} students")


The 1 subject was failed by 11 students
The 2 subject was failed by 12 students
The 3 subject was failed by 12 students
The 4 subject was failed by 11 students
The 5 subject was failed by 5 students


In [7]:
"""Calculating the highest subject mean"""
h_subject = np.max(subject_mean)
h_subject


64.3

In [8]:
""" The student, who performed the best in all subjects """
h_student = np.argmax(np.sum(marks, axis=1)) #argmax finds the index of the student
h_student
print("The student №", h_student+1, "has the best over-all marks", marks[h_student])

The student № 4 has the best over-all marks [89 63 34 73 79]
